version: '3'

services: 
    app:
        build: 
            context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 30s ./.docker/entrypoint.sh
        image: leandrojbraga/fullcycle-docker-desafionode-app:latest
        volumes: 
            - ./node:/home/node/app
        networks: 
            - desafionodenet
        depends_on:
            - db
    
    nginx:
        image: nginx:1.15.0-alpine
        container_name: nginx
        volumes: 
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/html:/var/www/html/
        ports:
            - "8080:80"
        networks: 
            - desafionodenet
        depends_on:
            - app
        
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql-dump:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - desafionodenet

networks: 
    desafionodenet:
        driver: bridge