FROM golang:1.16.0-stretch as builder

WORKDIR /go/src

ENV PATH="/go/bin:${PATH}"
ENV CGO_ENABLED=0

COPY . .

RUN go mod init github.com/leandrojbraga/fullcycle-docker-desafio && \
    GOOS=linux go build -o desafiogo -ldflags="-s -w"


FROM scratch

WORKDIR /app

COPY --from=builder /go/src/desafiogo .

ENTRYPOINT ["./desafiogo"]
